version: "2.2"
services:
    bazad:
        restart: always
        image: ewarehouse/bazad
        ports:
            - 0.0.0.0:11753:11753 # p2p
            - 127.0.0.1:11754:11754 # rpc
        volumes:
            - ./baza-data:/data
        # If you need block explorer API access (like for getblocks, gettransactionpool, etc.)
        # in RPC api uncomment following line
        # command: ["--enable-blockexplorer"]
    baza-wallet-api:
        restart: always
        image: ewarehouse/baza-wallet-api
        ports:
            - 127.0.0.1:8070:8070
        volumes:
            - ./baza-wallet-api-data:/data
        # IMP: Change the below environment variable's value before you start
        environment:
            - WALLET_API_RPC_PASSWORD=changethis
